import { IObject } from '../interfaces/object.interface';

export const poids: IObject = {
    PA: 100,
    PM: 90,
    Portée: 51,
    Invocations: 30,
    Force: 1,
    Intelligence: 1,
    Agilité: 1,
    Chance: 1,
    Vitalité: 0.2,
    Sagesse: 3,
    Puissance: 2,
    puiPiege: 2,
    Initiative: 0.1,
    '% Critique': 10,
    Soins: 10,
    doRen: 10,
    Dommages: 20,
    'Dommages Critiques': 5,
    'Dommages Neutre': 5,
    'Dommages Terre': 5,
    'Dommages Air': 5,
    'Dommages Feu': 5,
    'Dommages Eau': 5,
    'Dommages Poussée': 5,
    'Résistance Critiques': 2,
    'Résistance Neutre': 2,
    'Résistance Terre': 2,
    'Résistance Air': 2,
    'Résistance Feu': 2,
    'Résistance Eau': 2,
    'Résistance Poussée': 2,
    '% Résistance Neutre': 6,
    '% Résistance Terre': 6,
    '% Résistance Air': 6,
    '% Résistance Feu': 6,
    '% Résistance Eau': 6,
    Tacle: 4,
    Fuite: 4,
    Prospection: 3,
    'Retrait PA': 7,
    'Retrait PM': 7,
    'Esquive PA': 7,
    'Esquive PM': 7,
    Pod: 2.5
}
