import { IObject } from '../../interfaces/object.interface'; 

export const path = "../../assets/icons/runes/";

export const pathRunes: IObject = {
    'PA': "ga_pa.png",
    'PM': "ga_pmega_pa.png",
    'Portée': "po.png",
    'Invocations': "invo.png",
    'Force': "fo.png",
    'Intelligence': "ine.png",
    'Agilité': "age.png",
    'Chance': "cha.png",
    'Vitalité': "vi.png",
    'Sagesse': "sa.png",
    'Puissance': "pui.png",
    'puiPiege': "Trap_Power.svg",
    'Initiative': "ini.png",
    '% Critique': "cri.png",
    'Soins': "so.png",
    'doRen': "do_ren.png",
    'Dommages': "do.png",
    'Dommages Critiques': "do_cri.png",
    'Dommages Neutre': "do_neutre.png",
    'Dommages Terre': "do_terre.png",
    'Dommages Air': "do_air.png",
    'Dommages Feu': "do_feu.png",
    'Dommages Eau': "do_eau.png",
    'Dommages Poussée': "do_pou.png",
    'Résistance Critiques': "re_cri.png",
    'Résistance Neutre': "re_neutre.png",
    'Résistance Terre': "re_terre.png",
    'Résistance Air': "re_air.png",
    'Résistance Feu': "re_feu.png",
    'Résistance Eau': "re_eau.png",
    'Résistance Poussée': "re_pou.png",
    '% Résistance Neutre': "re_per_neutre.png",
    '% Résistance Terre': "re_per_terre.png",
    '% Résistance Air': "re_per_air.png",
    '% Résistance Feu': "re_per_feu.png",
    '% Résistance Eau': "re_per_eau.png",
    'Tacle': "tac.png",
    'Fuite': "fui.png",
    'Prospection': "prospe.png",
    'Retrait PA': "ret_pa.png",
    'Retrait PM': "ret_pme",
    'Esquive PA': "re_pa.png",
    'Esquive PM': "re_pme.png",
    'Pod': "pod.png"
}